build(deps): fix v8 missing include for numeric_t types
See https://github.com/envoyproxy/envoy/issues/29311.

The patch fixes include types for late clang (15.0.7) / gcc (13.2.1)
for Arch linux / Fedora, like in

    In file included from external/v8/src/torque/torque.cc:5:
    In file included from external/v8/src/torque/source-positions.h:10:
    In file included from external/v8/src/torque/contextual.h:10:
    In file included from external/v8/src/base/macros.h:12:
    external/v8/src/base/logging.h:154:26: error: use of undeclared identifier 'uint16_t'

Signed-off-by: Ivan Prisyazhnyy <john.koepi@gmail.com>