dynamic_modules: adds a lifetime param on EnvoyBuffer (#37880)
Commit Message: dynamic_modules: adds a lifetime param on EnvoyBuffer
Additional Description:

This adds a lifetime parameter to `EnvoyBuffer` as well as 
to getter methods that return it. Since the data structure only holds 
a raw pointer and length, if a mutable setter method of EnvoyHttpFilter 
is used, it can be invalid. Previously it was relatively easy to write
unsound logic
as there was no compile-time enforcement of invalidation.

This fixes the problem via life parameter and avoids making the
EnvoyBuffer
variables outliving the next setter methods. For example, using the
results returned
by `get_request_trailers` _after_ `set_request_trailer` results in
compilation
error:

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error[E0502]: cannot borrow `envoy_filter` as mutable because it is also borrowed as immutable
   --> test/extensions/dynamic_modules/test_data/rust/http.rs:118:5
    |
115 |     let all_trailers = envoy_filter.get_request_trailers();
    |                        ------------ immutable borrow occurs here
...
118 |     envoy_filter.set_request_trailer("new", b"value");
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
...
125 |     assert_eq!(all_trailers.len(), 4);
    |                ------------ immutable borrow later used here

```


Risk Level: low
Testing: existing tests
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

---------

Signed-off-by: Takeshi Yoneda <t.y.mathetake@gmail.com>