dubbo: fix compilation error.
There's a compilation error in dubbo, because the switch/case statement isn't handling the default case:

    contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc: In function 'absl::string_view Envoy::Extensions::NetworkFilters::GenericProxy::Codec::Dubbo::{anonymous}::responseStatusToStringView(Envoy::Extensions::Common::Dubbo::ResponseStatus)':
    contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc:38:1: error: control reaches end of non-void function [-Werror=return-type]
       38 | }
          | ^
    contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc: In function 'Envoy::Extensions::NetworkFilters::GenericProxy::StatusCode Envoy::Extensions::NetworkFilters::GenericProxy::Codec::Dubbo::{anonymous}::statusToGenericStatus(Envoy::Extensions::Common::Dubbo::ResponseStatus)':
    contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc:71:1: error: control reaches end of non-void function [-Werror=return-type]
       71 | }
          | ^
    cc1plus: all warnings being treated as errors

Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>