bazel: Only assume GCC on linux
macOS builds failed due to:

  error: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Werror,-Wunknown-warning-option]

Fix this by limiting the assumption of GCC by default to linux.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>