docs: we can only choose bazelisk via Homebrew
If we try to install bazelisk & bazel, there will be an error:

Error: Cannot install bazel because conflicting formulae are installed.
  bazelisk: because Bazelisk replaces the bazel binary

Please `brew unlink bazelisk` before continuing.

The rest of this doc recommends using bazelisk, so we replace bazel
here to bazelisk.

Signed-off-by: spacewander <spacewanderlzx@gmail.com>