tools: fix print_dependencies.py target error
Fix error if target is passed to tools/print_dependencies.py

For example:
$ tools/print_dependencies.py //envoy/ssl:handshaker_interface
Traceback (most recent call last):
  File "/envoy/envoy/tools/print_dependencies.py", line 48, in <module>
    for line in output.split('\n'):
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>