[Android] Replace uses of `StringJoiner` with `StringBuilder` (#2098)
Description: [StringJoiner](https://developer.android.com/reference/java/util/StringJoiner) was added in Android API level 24 but we still support back to API level 21, so this results in `NoClassDefFoundError` errors on devices running older Android versions.

Risk Level: Medium, this code is simple and unit tested.
Testing: Existing unit tests
Docs Changes: None
Release Notes: Added

Signed-off-by: JP Simard <jp@jpsim.com>