Rename PrintToString().
clang-tidy does not like PrintToString():
  error: invalid case style for function 'PrintToString' [readability-identifier-naming,-warnings-as-errors]

Unfortunately testing::PrintToStringParamName() requires this exact
name.  So define testParamToString() instead, and take a
TestParamInfo<ParserImpl> instead of a ParserImpl, so that it can be
used directly in INSTANTIATE_TEST_SUITE_P.

Signed-off-by: Bence Béky <bnc@google.com>