Windows: test compilation refresh
- Remove TestHeaderMapImplBase constructor that takes a list of
std::pair<LowerCaseString, std::string>
  - MSVC erroneously treats this as ambiguous. It appears the explicit
  attribute of the LowerCaseString constructor is incorrectly discarded.
  We are able to reproduce this in a minimal example and see that MSVC is wrong
  here: https://godbolt.org/z/VjgsAi
  - To mitigate, remove LowerCaseString based constructor since it is
  only used in tests, tests always use std::string
- Correct use of long in envoy_quic_alarm.cc, explicitly cast to int64_t
(long on Windows is 32 bits)
- `using std::string_literal::operator""s` is erroneously rejected by
MSVC, throwing error C4455.
  - Instead, simply utilize the namespace and continue to use the
  operator as is
  - operator usage could be replaced by `std::string (const char* s,
  size_t n)` constructor
  - See https://developercommunity.visualstudio.com/content/problem/270349/warning-c4455-issued-when-using-standardized-liter.html
  and other related duplicate issues that have not yet been resolved.

Signed-off-by: Sunjay Bhatia <sunjayb@vmware.com>
Co-authored-by: Sunjay Bhatia <sunjayb@vmware.com>
Signed-off-by: William A Rowe Jr <wrowe@vmware.com>
Co-authored-by: William A Rowe Jr <wrowe@vmware.com>