Use absl::variant as context type in createSinkPtr
Note that I had to pass validation_visitor manually because I can't get the
commented out version to compile. It reports errors such as this:

    user@12e5e5390487:/build/envoy$ bazel build -c dbg //source/exe:envoy-static --jobs=$(($(nproc) - 8))
    INFO: Invocation ID: 6ce2e3ec-2a4e-4903-ae6a-19f55cb7c645
    INFO: Analyzed target //source/exe:envoy-static (0 packages loaded, 0 targets configured).
    INFO: Found 1 target...
    ERROR: /build/envoy/source/extensions/common/tap/BUILD:23:17: Compiling source/extensions/common/tap/tap_config_base.cc failed: (Exit 1): clang-14 failed: error executing command (from target //source/extensions/common/tap:tap_config_base) /opt/llvm/bin/clang-14 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g ... (remaining 224 arguments skipped)

    Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
    source/extensions/common/tap/tap_config_base.cc:105:12: error: variable type 'Envoy::Server::Configuration::TransportSocketFactoryContext' is an abstract class
          auto tsf_context = tsf_context_ref.get();
               ^
    source/extensions/common/tap/tap_config_base.cc:116:7: error: variable type 'Envoy::Server::Configuration::FactoryContext' is an abstract class
          http_context = http_context_ref.get(); config =
          ^

Signed-off-by: Ashish Banerjee <ashish.banerjee@solo.io>