mobile: Upgrade to the latest JDK 11 for ktfmt
Occassionally I've seen an error with `NoClassDefFoundError` when running
`ktfmt` with an older JDK 11. After updating to the latest JDK 11, I no
longer see the error.

Signed-off-by: Fredy Wijaya <fredyw@google.com>