mobile/ci: Fix iOS_build failures
The error:

```
ERROR: /Users/runner/work/envoy/envoy/mobile/WORKSPACE:98:18: fetching android_sdk_repository rule //external:androidsdk: Android SDK api level 30 was requested but it is not installed in the Android SDK at /Users/runner/Library/Android/sdk. The api levels found were [34, 33, 32, 31]. Please choose an available api level or install api level 30 from the Android SDK Manager.
```

This PR is a workaround to install Android SDK 30 even though it's not
used for building iOS apps, that's because mobile/WORKSPACE expects the
Android SDK 30 to be available and GitHub Runner image no longer
includes Android SDK 30. See https://github.com/actions/runner-images/issues/8952.
Passing `--android` in the `./ci/mac_ci_setup.sh` will install the Android SDK 30.

Signed-off-by: Fredy Wijaya <fredyw@google.com>