mysql_utils.cc: access EnvoyException by reference.
Compilation fails because Envoy::EnvoyException values are caught by
value. Change the catching to references to fix the issue.

source/extensions/filters/network/mysql_proxy/mysql_utils.cc:100:27: error: catching polymorphic type 'class Envoy::EnvoyException' by value [-Werror=catch-value=]

Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>