contrib: drop deprecated repository arg from per_worker_subset (#47713)
<!--
!!!ATTENTION!!!

If you are fixing **any** crash or **any** potential security issue,
**do not
open a pull request**.

Instead, please
[open a GitHub Security
Advisory](https://github.com/envoyproxy/envoy/security/advisories/new)
(preferred). Alternatively, you may email
envoy-security@googlegroups.com.

Thank you in advance for helping to keep Envoy secure.

!!!ATTENTION!!!

For an explanation of how to fill out the fields, please see the
relevant section
in
[PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

!!!ATTENTION!!!

Please check the [use of generative AI
policy](https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md?plain=1#L41).

You may use generative AI only if you fully understand the code. You
need to disclose
this usage in the PR description to ensure transparency.
-->

main ci is broken:
```
  ERROR: /source/contrib/per_worker_subset/load_balancing_policies/source/BUILD:12:17: configurable attribute "deps" in //contrib/per_worker_subset/load_balancing_policies/source:per_worker_subset_lb_lib doesn't match this configuration: envoy_cc_library: The `repository` argument is deprecated and is currently ignored.
  Use the `@envoy//bazel` label_flag overrides instead, for example `--@envoy//bazel:test_main=@your_repo//:custom_test_main`.
   Got "@envoy".
```

Commit Message:
Additional Description:
Risk Level: low

Signed-off-by: Boteng Yao <botengyao@gmail.com>