types_async_client.h: fix deprecated defaulted copy ctor
Fixes an oss-fuzz Envoy compilation error:
```
Step #3 - "compile-afl-address-x86_64": Execution platform: @local_config_platform//:host
Step #3 - "compile-afl-address-x86_64": In file included from source/extensions/filters/http/ext_proc/client_impl.cc:1:
Step #3 - "compile-afl-address-x86_64": In file included from ./source/extensions/filters/http/ext_proc/client_impl.h:11:
Step #3 - "compile-afl-address-x86_64": [1m./source/common/grpc/typed_async_client.h:38:3: [0m[0;1;31merror: [0m[1mdefinition of implicit copy assignment operator for 'AsyncStream<envoy::service::ext_proc::v3::ProcessingRequest>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy][0m
Step #3 - "compile-afl-address-x86_64":   AsyncStream(const AsyncStream& other) = default;
Step #3 - "compile-afl-address-x86_64": [0;1;32m  ^
Step #3 - "compile-afl-address-x86_64": [0m[1msource/extensions/filters/http/ext_proc/client_impl.cc:34:11: [0m[0;1;30mnote: [0min implicit copy assignment operator for 'Envoy::Grpc::AsyncStream<envoy::service::ext_proc::v3::ProcessingRequest>' first required here[0m
Step #3 - "compile-afl-address-x86_64":   stream_ = client_.start(*descriptor, *this, options);
Step #3 - "compile-afl-address-x86_64": [0;1;32m          ^
Step #3 - "compile-afl-address-x86_64": [0m1 error generated.
```

Signed-off-by: disconnect3d <dominik.b.czarnota@gmail.com>