ci: fix health check integration test compilation (#40406)
## Description

This PR fixes the compilation issue for `health_check_integration_test`
which is complaining about,
```
error: no member named 'TypeUrl' in namespace 'Envoy::Config'; did you mean 'TypeUtil'?
```

This happened due to a race condition when the PR with additional tests
using `TypeUrl` and a PR to change `TypeUrl` => `TestTypeUrl` went in
side by side and the cache was probably stale.

---

**Commit Message:** ci: fix health check integration test compilation
**Additional Description:** Fixes compilation for
`health_check_integration_test` by switching `TypeUrl` to use new
`TestTypeUrl`.
**Risk Level:** Low
**Testing:** CI
**Docs Changes:** N/A
**Release Notes:** N/A

---------

Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>