Let clang-format order headers (#43348)
Commit Message: Let clang-format order headers
Additional Description: Before this change, clang-format is configured
to ignore header order. There is [this
config](https://github.com/envoyproxy/envoy/blob/6bf1fe744a38d4aa8a9324e81add6a3e559b8063/tools/code_format/config.yaml#L386-L393)
and [this
code](https://github.com/envoyproxy/envoy/blob/6bf1fe744a38d4aa8a9324e81add6a3e559b8063/tools/code_format/header_order.py#L21-L102)
for reordering or order-checking the headers. The current workflow,
therefore, is you make your changes, you run the git push hook, it takes
ages and then gives a horrible error message like this:
```
ERROR: header_order.py check failed for file: ./test/extensions/filters/http/bandwidth_limit/filter_test.cc
5d4
< #include "test/test_common/status_utility.h"
6a6
> #include "test/test_common/status_utility.h"

ERROR:   ./test/extensions/filters/http/bandwidth_limit/filter_test.cc:5
ERROR:   ./test/extensions/filters/http/bandwidth_limit/filter_test.cc:6
ERROR: check format failed. run 'bazel run //tools/code_format:check_format -- fix'
```
Then you run that tool which takes another multiple minutes to apply the
fix.

With clang-format doing the same ordering, every time I save in vscode
the headers get correctly ordered, and it therefore doesn't anger the
git push hook check.

This change removes `header_order.py` and all calls into it; the one
place its behavior conflicts with clang-format is on identifying the
"main" header, which clang-format actually does better (see, e.g.
`source/exe/win32/platform_impl.cc` for which clang-format correctly
places the key header at the top, vs. header_order.py did not recognize
it because the path wasn't a perfect match.)

Other cleanups inspired by this change include full-pathing several
headers that were included using local-paths, contrary to style, which
clang-tidy rearranged and therefore brought attention to.
Risk Level: Virtually none, unless someone has done something bonkers
where header order makes a difference.
Testing: Existing tests should all continue to pass.
I also tried rearranging headers in an existing file in various ways,
and clang-format-on-save consistently put them back in the "correct"
order (matching what the python script required, in all cases except the
ones with the unusual key headers).
Applied to everything with `find . -name '*.cc' -o -name '*.h' | xargs
clang-format -i`
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

---------

Signed-off-by: Raven Black <ravenblack@dropbox.com>