mcp: fix mcp_json_rest_bridge_filter build issue (#45739)
## Description

Master is broken right now due to PR #45690 changing
`McpJsonRestBridgePerRoute.tool_config` from singular to repeated
`ServerToolConfig`. It updated the per-route constructor and
`getToolsListHttpRule()` to iterate.
```
./source/extensions/filters/http/mcp_json_rest_bridge/mcp_json_rest_bridge_filter.h:92:12: error: no viable conversion from returned value of type 'const ::google::protobuf::RepeatedPtrField< ::envoy::extensions::filters::http::mcp_json_rest_bridge::v3::ServerToolConfig>' to function return type 'const envoy::extensions::filters::http::mcp_json_rest_bridge::v3::ServerToolConfig'
   92 |     return proto_config_.tool_config();
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This PR is trying to fix the issue.

---

**Commit Message:** mcp: fix mcp_json_rest_bridge_filter build
**Risk Level:** Low
**Testing:** CI
**Docs Changes:** N/A
**Release Notes:** N/A

Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>