tools: bootstrap: add support for symlinks in pwd
Currently bootstrap does not support paths with symlinks.

For example:

ln -s envoy/ envoy-symlink
cd envoy-symlink
support/bootstrap
ERROR: this script must be run at the root of the envoy source tree

$ echo $PWD
/envoy-symlink
$ echo "$(git rev-parse --show-toplevel)"
/envoy

Solution is to use pwd -P (physical: avoid all symlinks) instead of $PWD

$ echo "$(pwd -P)"
/envoy

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>