Fix a compilation error for com_lightstep_tracer_cpp
When compiling the external repo com_lightstep_tracer_cpp on arm64
by GCC, it would show the following error:

com_lightstep_tracer_cpp/src/common/BUILD:173:1: C++ compilation of rule
'@com_lightstep_tracer_cpp//src/common:utility_lib' failed (Exit 1) gcc
failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE
-fstack-protector -Wall -Wunused-but-set-parameter ...
external/com_lightstep_tracer_cpp/src/common/utility.cpp:76:20: error:
comparison is always true due to limited range of data type
[-Werror=type-limits]
         if ('\x00' <= c && c <= '\x1f') {
                 ~~~~~~~^~~~
cc1plus: all warnings being treated as errors
Target //source/exe:envoy-static failed to build

This warning is due to the explanation for 'char' type on arm64 is explained as
'unsigned char', but for x86_64, it's for 'signed char'.
More details about this warning could be found at:
https://stackoverflow.com/questions/757482/\
comparison-is-always-true-due-to-limited-range-of-data-type-warning-in-c

This patch fixes the above error by adding a forced 'signed-char' flag
to copts when building lightstep_tracer_cpp package which would force to
use the 'singed char' explanation to 'char' type.

Signed-off-by: Trevor Tao <trevor.tao@arm.com>