deps: revert cryptography module update (#41160)
## Description

This PR reverts the cryptography module upgrade done as part of [this
PR](https://github.com/envoyproxy/envoy/pull/41140).

It's throwing these errors in the build:
```
from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /mnt/engflow/worker/work/1/exec/bazel-out/k8-fastbuild/bin/test/integration/python/hotrestart_handoff_test.runfiles/base_pip3_cryptography/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
```

---

**Commit Message:** deps: revert cryptography module update
**Additional Description:** Reverting a problematic dependency upgrade
which is creating issues.
**Risk Level:** N/A
**Testing:** CI
**Docs Changes:** N/A
**Release Notes:** N/A

Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>