Revert "bazel: change bazelisk for M1 support (#1966)" (#1998)
This reverts commit aeab7fe443e41a06687137a52002223f084f9db8.

Unfortunately still not working on M1.

E.g.

```
$ ./bazelw build //library/common:envoy_main_interface_lib
ERROR: While resolving toolchains for target @com_envoyproxy_protoc_gen_validate//:protoc-gen-validate: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//library/common:envoy_main_interface_lib' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
```

Signed-off-by: JP Simard <jp@jpsim.com>